#define pi                          3.1415926535
#define UPDATE_PERIOD              20
#define ENABLE                    LOW
#define DISABLE                  HIGH
#define BAUDRATE               115200
#define X_DIRECTION              HIGH
#define Y_DIRECTION              HIGH
#define DEFAULT_STROBE_PERIOD  120000
#define DEFAULT_STROBE_LENGTH    5000
#define DEFAULT_LIGHT_INT         255
#define LIGHT_ON                  LOW
#define LIGHT_OFF                HIGH

#define X_STEPS_PER_DEG            42.637f
#define X_STEPS_PER_ENC_PULSE      32.0f
#define Y_STEPS_PER_DEG            31.2f
#define Y_STEPS_PER_ENC_PULSE      32.0f
#define X_MIN                    -90.0f
#define X_MAX                     90.0f
#define Y_MIN                    -135.0f
#define Y_MAX                     135.0f
#define MIN_SPEED                   0.1f
#define MAX_SPEED                 120.0f
